### ISSUE TITLE
Title/snap images use unideal resolutions

### ISSUE THREAD

**Issue by dstaley** [codewario/PocketLibraryImageConversion#3]
The GBA title/snap image set uses a resolution of 165x110, whereas the original source image uses a resolution of 240x160. The GB title/snap image set uses a resolution of 165x149, which is larger than the GameBoy's original resolution of 160x144.

Image from the most recent release:

![libretro](https://user-images.githubusercontent.com/88163/213363577-b837fb42-e496-4089-8db7-fda5a76d2e1b.png)

Original title image (pulled from another image library):

![spiritualized](https://user-images.githubusercontent.com/88163/213363705-fde65600-0bdd-46e8-8251-61c1fb7ee053.png)

Smaller image on the Pocket:

![libretro](https://user-images.githubusercontent.com/88163/213366670-47daf4c5-48b9-4c62-9419-b4ad1a952031.jpg)

Larger image on the Pocket:

![original](https://user-images.githubusercontent.com/88163/213366713-dfef818d-2c76-4010-b3df-73a9ddcf08bc.jpg)

Ideally, title/snap images should be stored in their original resolution rather than being resized. For box art images, it would probably be best to resize them to 240 pixels wide since that's the largest known-good image width.

**Comment by codewario** [comment]
It's been a while since I wrote this, but it was not long after Libraries was released. If I remember correctly, I believe I had to scale the image down because the images were getting cut off, but this may have been a bug that a firmware update fixed. I'll try and get some time to address this.

**Comment by codewario** [comment]
I addressed this by opting to keep the original resolution for title screens and snaps, only scaling when it comes to the box art.
